import {
  Bold,
  Code,
  Heading1,
  Heading2,
  Heading3,
  Italic,
  List,
  ListOrdered,
  Minus,
  Quote,
  Redo,
  SquareCode,
  Strikethrough,
  Underline,
  Undo,
} from "lucide-react";

export const toolbarIcons = {
  bold: <Bold size={16} strokeWidth={1.5} />,
  italic: <Italic size={16} strokeWidth={1.5} />,
  underline: <Underline size={16} strokeWidth={1.5} />,
  strikethrough: <Strikethrough size={16} strokeWidth={1.5} />,
  heading1: <Heading1 size={16} strokeWidth={1.5} />,
  heading2: <Heading2 size={16} strokeWidth={1.5} />,
  heading3: <Heading3 size={16} strokeWidth={1.5} />,
  bulletList: <List size={16} strokeWidth={1.5} />,
  orderedList: <ListOrdered size={16} strokeWidth={1.5} />,
  blockquote: <Quote size={16} strokeWidth={1.5} />,
  code: <Code size={16} strokeWidth={1.5} />,
  codeBlock: <SquareCode size={16} strokeWidth={1.5} />,
  horizontalRule: <Minus size={16} strokeWidth={1.5} />,
  undo: <Undo size={16} strokeWidth={1.5} />,
  redo: <Redo size={16} strokeWidth={1.5} />,
};
